repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0  # Use the specific version of Black you want to pin to
    hooks:
      - id: black
        language_version: python3  # Should match the Python version you're using
        exclude: '/migrations/'

